site_name: Ecliptic Seasons
site_url: https://example.com
site_description: A documentation for Ecliptic Seasons project
site_author: jianzoushihu
repo_url: https://github.com/joe-vettek/Ecliptic-Seasons
repo_name: Ecliptic Seasons

theme:
  name: 'material'
  language: 'en'


nav:
  - Home:
      - English:
          - Index: 'en/index.md'
          - Quickly learn about this mod: 'en/quickly_start.md'
          - Season: 'en/season.md'
          - Climate: 'en/climate.md'
          - Crop: 'en/crop.md'
          - Configuration: 'en/configuration.md'
          - Datapack Base: 'en/datapack.md'
          - Frequent Question: 'en/question.md'
          - Custom:
              - Model Definitions: 'en/custom/model_definitions.md'
              - Snowy Block Models: 'en/custom/snow_definitions.md'
              - Seasonal Block Models: 'en/custom/season_definitions.md'
              - Seasonal Textures Changes of Models: 'en/custom/season_textures.md'
              - Fallen Leaves Particles: 'en/custom/fallen_leaves.md'
              - Seasonal Biome Ambient: 'en/custom/ambient.md'
              - Seasonal Biome Color: 'en/custom/biome_colors.md'
          - Data packs:
              - Crop Growth: 'en/data/crop.md'
              - Agro Climate Zones: 'en/data/agro_climate.md'
              - Biome Climate Settings: 'en/data/biome_climate_setting.md'
              - Snow Timing: 'en/data/snow_term.md'
              - Biome Weather: 'en/data/biome_rain.md'
              - Modify Season Mapping: 'en/data/season_cycle.md'
              - Adjust Seasonal Display Information: 'en/data/season_phase.md'
              - Humidity Control: 'en/data/humidity_control.md'
              - Season Quests: 'en/data/season_quest.md'
              - Loot with Seasons: 'en/data/loot.md'
              - Weather Region: 'en/data/weather_region.md'
              - Seasonal Changes and Block Variations: 'en/data/season_definitions.md'
              - Humidity Structure: 'en/data/wetter.md'
      - 中文:
          - 首页: 'zh/index.md'
          - 新手须知: 'zh/quickly_start.md'
          - 季节: 'zh/season.md'
          - 气候: 'zh/climate.md'
          - 作物: 'zh/crop.md'
          - 配置: 'zh/configuration.md'
          - 数据包基本: 'zh/datapack.md'
          - 常见问题: 'zh/question.md'
          - 自定义:
              - 模型映射: 'zh/custom/model_definitions.md'
              - 覆雪方块定义与模型: 'zh/custom/snow_definitions.md'
              - 四季模型: 'zh/custom/season_definitions.md'
              - 季节贴图变化: 'zh/custom/season_textures.md'
              - 落叶: 'zh/custom/fallen_leaves.md'
              - 季节音效: 'zh/custom/ambient.md'
              - 群系颜色: 'zh/custom/biome_colors.md'
          - 数据包:
              - 作物生长: 'zh/data/crop.md'
              - 农业气候区: 'zh/data/agro_climate.md'
              - 群系气候设定: 'zh/data/biome_climate_setting.md'
              - 下雪时间: 'zh/data/snow_term.md'
              - 群系天气: 'zh/data/biome_rain.md'
              - 修改季节名称映射: 'zh/data/season_cycle.md'
              - 调整季节显示信息: 'zh/data/season_phase.md'
              - 湿度调整: 'zh/data/humidity_control.md'
              - 季节任务: 'zh/data/season_quest.md'
              - 战利品表与季节条件: 'zh/data/loot.md'
              - 天气分区: 'zh/data/weather_region.md'
              - 季节与方块变化: 'zh/data/season_definitions.md'
              - 湿度调整结构: 'zh/data/wetter.md'


markdown_extensions:
  - toc:
      permalink: true
  - admonition

extra_css:
  - _static/css/custom.css
extra_javascript:
  - _static/js/custom.js

docs_dir: 'source'

extra:
  static_path: [ '[_static]' ]
  alternate:
    - name: English
      link: /en/latest/en/
      lang: en
    - name: 中文
      link: /en/latest/zh/
      lang: zh
plugins:
  - search


